ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

-- CRIAÇÃO DE TABELAS E CHAVES

CREATE TABLE CLIENTES(
  ID_CLIENTE     NUMBER(10)   NOT NULL,
  NOME           VARCHAR2(100),
  DATA_CADASTRO  DATE,
  CPF_CNPJ       VARCHAR2(14),
  EMAIL          VARCHAR2(100)
);

ALTER TABLE CLIENTES
  ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE);

CREATE TABLE FUNCIONARIOS(
  ID_FUNCIONARIO NUMBER(10)   NOT NULL,
  NOME           VARCHAR2(100) NOT NULL,
  DATA_ADMISSAO  DATE          NOT NULL,
  CPF            VARCHAR2(11)  NOT NULL,
  EMAIL          VARCHAR2(100) NOT NULL,
  CARGA_HORARIA  NUMBER(10)    NOT NULL
);

ALTER TABLE FUNCIONARIOS
  ADD CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (ID_FUNCIONARIO);

CREATE TABLE TELEFONE(
  ID_TELEFONE    NUMBER(10)    NOT NULL,
  NUMERO         VARCHAR2(20)  NOT NULL,
  DDD            VARCHAR2(3)   NOT NULL,
  DDI            VARCHAR2(4)   NOT NULL,
  ID_CLIENTE     NUMBER(10),
  ID_FUNCIONARIO NUMBER(10)
);

ALTER TABLE TELEFONE
  ADD CONSTRAINT PK_TELEFONE PRIMARY KEY (ID_TELEFONE);

ALTER TABLE TELEFONE
  ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE TELEFONE
  ADD CONSTRAINT FK_FUNCIONARIO_TELEFONE FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

CREATE TABLE UF(
  ID_UF  NUMBER(10)   NOT NULL,
  SIGLA  VARCHAR2(2)  NOT NULL,
  NOME   VARCHAR2(40) NOT NULL
);

ALTER TABLE UF
  ADD CONSTRAINT PK_UF PRIMARY KEY (ID_UF);

CREATE TABLE CIDADE(
  ID_CIDADE NUMBER(10)   NOT NULL,
  NOME      VARCHAR2(60) NOT NULL,
  ID_UF     NUMBER(10)   NOT NULL
);

ALTER TABLE CIDADE
  ADD CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE);

ALTER TABLE CIDADE
  ADD CONSTRAINT FK_UF_CIDADE FOREIGN KEY (ID_UF)
  REFERENCES UF(ID_UF);

CREATE TABLE ENDERECO(
  ID_ENDERECO    NUMBER(10)   NOT NULL,
  LOGRADOURO     VARCHAR2(50),
  NUMERO         NUMBER(10)   NOT NULL,
  BAIRRO         VARCHAR2(50),
  CEP            VARCHAR2(10) NOT NULL,
  ID_CLIENTE     NUMBER(10),
  ID_FUNCIONARIO NUMBER(10),
  ID_CIDADE      NUMBER(10)   NOT NULL
);

ALTER TABLE ENDERECO
  ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO);

ALTER TABLE ENDERECO
  ADD CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE ENDERECO
  ADD CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

ALTER TABLE ENDERECO
  ADD CONSTRAINT FK_CIDADE_ENDERECO FOREIGN KEY (ID_CIDADE)
  REFERENCES CIDADE(ID_CIDADE);

CREATE TABLE CARGO(
  ID_CARGO NUMBER(10)   NOT NULL,
  NOME     VARCHAR2(50) NOT NULL
);

ALTER TABLE CARGO
  ADD CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO);

CREATE TABLE FUNCIONARIO_CARGO(
  ID_FUNCIONARIO_CARGO NUMBER(10) NOT NULL,
  ID_FUNCIONARIO       NUMBER(10) NOT NULL,
  ID_CARGO             NUMBER(10) NOT NULL,
  DATA_INGRESSO        DATE       NOT NULL,
  DATA_SAIDA           DATE
);

ALTER TABLE FUNCIONARIO_CARGO
  ADD CONSTRAINT PK_FUNCIONARIO_CARGO PRIMARY KEY (ID_FUNCIONARIO_CARGO);

ALTER TABLE FUNCIONARIO_CARGO
  ADD CONSTRAINT FK_FC_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

ALTER TABLE FUNCIONARIO_CARGO
  ADD CONSTRAINT FK_FC_ID_CARGO FOREIGN KEY (ID_CARGO)
  REFERENCES CARGO(ID_CARGO);

CREATE TABLE FORNECEDOR(
  ID_FORNECEDOR       NUMBER(10)   NOT NULL,
  RAZAO_SOCIAL        VARCHAR2(70) NOT NULL,
  CNPJ                VARCHAR2(14) NOT NULL,
  NOME_REPRESENTANTE  VARCHAR2(70) NOT NULL
);

ALTER TABLE FORNECEDOR
  ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR);

CREATE TABLE PRODUTO_COMBUSTIVEL(
  ID_PRODUTO_COMBUSTIVEL NUMBER(10)   NOT NULL,
  NOME                   VARCHAR2(30) NOT NULL,
  PRECO_VENDA_LITRO      NUMBER(9,2)  NOT NULL
);

ALTER TABLE PRODUTO_COMBUSTIVEL
  ADD CONSTRAINT PK_PRODUTO_COMBUSTIVEL PRIMARY KEY (ID_PRODUTO_COMBUSTIVEL);

CREATE TABLE FORNECIMENTO_COMBUSTIVEL(
  ID_FORNECIMENTO_COMBUSTIVEL NUMBER(10)  NOT NULL,
  ID_PRODUTO_COMBUSTIVEL      NUMBER(10)  NOT NULL,
  ID_FORNECEDOR               NUMBER(10)  NOT NULL,
  QUANTIDADE_LITROS           NUMBER(12,3) NOT NULL,
  VALOR                       NUMBER(9,2)  NOT NULL,
  DATA_FORNECIMENTO           DATE         NOT NULL
);

ALTER TABLE FORNECIMENTO_COMBUSTIVEL
  ADD CONSTRAINT PK_FORNECIMENTO_COMBUSTIVEL PRIMARY KEY (ID_FORNECIMENTO_COMBUSTIVEL);

ALTER TABLE FORNECIMENTO_COMBUSTIVEL
  ADD CONSTRAINT FK_FC_ID_PRODUTO_COMBUSTIVEL FOREIGN KEY (ID_PRODUTO_COMBUSTIVEL)
  REFERENCES PRODUTO_COMBUSTIVEL(ID_PRODUTO_COMBUSTIVEL);

ALTER TABLE FORNECIMENTO_COMBUSTIVEL
  ADD CONSTRAINT FK_FC_ID_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
  REFERENCES FORNECEDOR(ID_FORNECEDOR);

CREATE TABLE BOMBAS(
  ID_BOMBA   NUMBER(10)    NOT NULL,
  DESCRICAO  VARCHAR2(150) NOT NULL
);

ALTER TABLE BOMBAS
  ADD CONSTRAINT PK_BOMBAS PRIMARY KEY (ID_BOMBA);

CREATE TABLE BICOS(
  ID_BICO               NUMBER(10)    NOT NULL,
  DESCRICAO             VARCHAR2(150) NOT NULL,
  ID_BOMBA              NUMBER(10)    NOT NULL,
  ID_PRODUTO_COMBUSTIVEL NUMBER(10)   NOT NULL
);

ALTER TABLE BICOS
  ADD CONSTRAINT PK_BICOS PRIMARY KEY (ID_BICO);

ALTER TABLE BICOS
  ADD CONSTRAINT FK_BICOS_ID_PRODUTO_COMBUSTIVEL FOREIGN KEY (ID_PRODUTO_COMBUSTIVEL)
  REFERENCES PRODUTO_COMBUSTIVEL(ID_PRODUTO_COMBUSTIVEL);

ALTER TABLE BICOS
  ADD CONSTRAINT FK_BICOS_ID_BOMBA FOREIGN KEY (ID_BOMBA)
  REFERENCES BOMBAS(ID_BOMBA);

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

CREATE TABLE AFERICOES_BICO(
  ID_AFERICAO        NUMBER(10)   NOT NULL,
  DATA_HORA_AFERICAO DATE         NOT NULL,
  LEITURA_ABERTURA   NUMBER(12,3) NOT NULL,
  LEITURA_FECHAMENTO NUMBER(12,3) NOT NULL,
  ID_FUNCIONARIO     NUMBER(10)   NOT NULL,
  ID_BICO            NUMBER(10)   NOT NULL
);

ALTER TABLE AFERICOES_BICO
  ADD CONSTRAINT PK_AFERICAO PRIMARY KEY (ID_AFERICAO);

ALTER TABLE AFERICOES_BICO
  ADD CONSTRAINT FK_AFERICAO_ID_BICO FOREIGN KEY (ID_BICO)
  REFERENCES BICOS(ID_BICO);

ALTER TABLE AFERICOES_BICO
  ADD CONSTRAINT FK_AFERICAO_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

CREATE TABLE PRODUTO_LOJA(
  ID_PRODUTO_LOJA        NUMBER(10)   NOT NULL,
  QTD_ESTOQUE            NUMBER(10)   NOT NULL,
  NOME                   VARCHAR2(100) NOT NULL,
  PRECO_VENDA_UNITARIO   NUMBER(9,2)   NOT NULL
);

ALTER TABLE PRODUTO_LOJA
  ADD CONSTRAINT PK_PRODUTO_LOJA PRIMARY KEY (ID_PRODUTO_LOJA);

CREATE TABLE FORNECIMENTO_PRODUTO_LOJA(
  ID_FORNECIMENTO_PRODUTO_LOJA NUMBER(10) NOT NULL,
  ID_PRODUTO_LOJA              NUMBER(10) NOT NULL,
  ID_FORNECEDOR                NUMBER(10) NOT NULL,
  QUANTIDADE                   NUMBER(10) NOT NULL,
  VALOR_UNITARIO               NUMBER(9,2) NOT NULL,
  DATA_FORNECIMENTO_PRODUTO    DATE        NOT NULL
);

ALTER TABLE FORNECIMENTO_PRODUTO_LOJA
  ADD CONSTRAINT PK_FORNECIMENTO_PRODUTO_LOJA PRIMARY KEY (ID_FORNECIMENTO_PRODUTO_LOJA);

ALTER TABLE FORNECIMENTO_PRODUTO_LOJA
  ADD CONSTRAINT FK_FPL_ID_PRODUTO_LOJA FOREIGN KEY (ID_PRODUTO_LOJA)
  REFERENCES PRODUTO_LOJA(ID_PRODUTO_LOJA);

ALTER TABLE FORNECIMENTO_PRODUTO_LOJA
  ADD CONSTRAINT FK_FPL_ID_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)
  REFERENCES FORNECEDOR(ID_FORNECEDOR);

CREATE TABLE FORMA_PAGAMENTO(
  ID_FORMA_PAGAMENTO NUMBER(10)  NOT NULL,
  NOME              VARCHAR2(20)
);

ALTER TABLE FORMA_PAGAMENTO
  ADD CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY (ID_FORMA_PAGAMENTO);

CREATE TABLE COMPRA_VENDA(
  ID_COMPRA_VENDA       NUMBER(10)  NOT NULL,
  DATA_COMPRA_VENDA     DATE        NOT NULL,
  ID_CLIENTE            NUMBER(10)  NOT NULL,
  ID_FUNCIONARIO        NUMBER(10)  NOT NULL,
  QUANTIDADE_COMBUSTIVEL NUMBER(12,3),
  VALOR_PAGO_COMBUSTIVEL NUMBER(9,2),
  ID_BICO               NUMBER(10)
);

ALTER TABLE COMPRA_VENDA
  ADD CONSTRAINT PK_COMPRA_VENDA PRIMARY KEY (ID_COMPRA_VENDA);

ALTER TABLE COMPRA_VENDA
  ADD CONSTRAINT FK_CV_ID_BICO FOREIGN KEY (ID_BICO)
  REFERENCES BICOS(ID_BICO);

ALTER TABLE COMPRA_VENDA
  ADD CONSTRAINT FK_CV_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE COMPRA_VENDA
  ADD CONSTRAINT FK_CV_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);

CREATE TABLE COMPRA_VENDA_PRODUTO_LOJA(
  ID_COMPRA_VENDA_PRODUTO_LOJA NUMBER(10) NOT NULL,
  QUANTIDADE                   NUMBER(10) NOT NULL,
  VALOR_UNIDADE                NUMBER(9,2) NOT NULL,
  ID_PRODUTO_LOJA              NUMBER(10) NOT NULL,
  ID_COMPRA_VENDA              NUMBER(10) NOT NULL
);

ALTER TABLE COMPRA_VENDA_PRODUTO_LOJA
  ADD CONSTRAINT PK_CV_PRODUTO_LOJA PRIMARY KEY (ID_COMPRA_VENDA_PRODUTO_LOJA);

ALTER TABLE COMPRA_VENDA_PRODUTO_LOJA
  ADD CONSTRAINT FK_CVPL_ID_PRODUTO_LOJA FOREIGN KEY (ID_PRODUTO_LOJA)
  REFERENCES PRODUTO_LOJA(ID_PRODUTO_LOJA);

ALTER TABLE COMPRA_VENDA_PRODUTO_LOJA
  ADD CONSTRAINT FK_CVPL_ID_COMPRA_VENDA FOREIGN KEY (ID_COMPRA_VENDA)
  REFERENCES COMPRA_VENDA(ID_COMPRA_VENDA);

CREATE TABLE COMPRA_VENDA_FORMA_PAGAMENTO(
  ID_COMPRA_VENDA_FORMA_PAGAMENTO NUMBER(10) NOT NULL,
  ID_COMPRA_VENDA                 NUMBER(10) NOT NULL,
  ID_FORMA_PAGAMENTO              NUMBER(10) NOT NULL,
  VALOR_PAGO                      NUMBER(9,2)
);

ALTER TABLE COMPRA_VENDA_FORMA_PAGAMENTO
  ADD CONSTRAINT PK_CV_FORMA_PAGAMENTO PRIMARY KEY (ID_COMPRA_VENDA_FORMA_PAGAMENTO);

ALTER TABLE COMPRA_VENDA_FORMA_PAGAMENTO
  ADD CONSTRAINT FK_CVFP_ID_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO)
  REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO);

ALTER TABLE COMPRA_VENDA_FORMA_PAGAMENTO
  ADD CONSTRAINT FK_CVFP_ID_COMPRA_VENDA FOREIGN KEY (ID_COMPRA_VENDA)
  REFERENCES COMPRA_VENDA(ID_COMPRA_VENDA);

CREATE TABLE ALERTAS_REABASTECIMENTO (
  ID_ALERTA             NUMBER(10)   NOT NULL,
  ID_PRODUTO_LOJA       NUMBER(10)   NOT NULL,
  DATA_ALERTA           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  ESTOQUE_NO_ALERTA     NUMBER(10)   NOT NULL
);

ALTER TABLE ALERTAS_REABASTECIMENTO
  ADD CONSTRAINT PK_ALERTAS_REABASTECIMENTO
  PRIMARY KEY (ID_ALERTA);

ALTER TABLE ALERTAS_REABASTECIMENTO
  ADD CONSTRAINT FK_AR_ID_PRODUTO_LOJA
  FOREIGN KEY (ID_PRODUTO_LOJA)
  REFERENCES PRODUTO_LOJA (ID_PRODUTO_LOJA);

CREATE TABLE GRATIFICACOES (
  ID_GRATIFICACAO  NUMBER(10)    NOT NULL,
  ID_FUNCIONARIO   NUMBER(10)    NOT NULL,
  DATA_PAGAMENTO   DATE          NOT NULL,
  VALOR_PAGAMENTO  NUMBER(10,2)  NOT NULL,
  DESCRICAO        VARCHAR2(150)
);

ALTER TABLE GRATIFICACOES
  ADD CONSTRAINT PK_GRATIFICACOES
  PRIMARY KEY (ID_GRATIFICACAO);

ALTER TABLE GRATIFICACOES
  ADD CONSTRAINT FK_GRATIFICACOES_FUNCIONARIO
  FOREIGN KEY (ID_FUNCIONARIO)
  REFERENCES FUNCIONARIOS (ID_FUNCIONARIO);

-- SEQUÊNCIAS 

CREATE SEQUENCE SQ_AFERICOES_BICO;
CREATE SEQUENCE SQ_BICOS;
CREATE SEQUENCE SQ_BOMBAS;
CREATE SEQUENCE SQ_CARGO;
CREATE SEQUENCE SQ_CIDADE;
CREATE SEQUENCE SQ_CLIENTES;
CREATE SEQUENCE SQ_COMPRA_VENDA;
CREATE SEQUENCE SQ_COMPRA_VENDA_FORMA_PAGAMENTO;
CREATE SEQUENCE SQ_COMPRA_VENDA_PRODUTO_LOJA;
CREATE SEQUENCE SQ_ENDERECO;
CREATE SEQUENCE SQ_FORMA_PAGAMENTO;
CREATE SEQUENCE SQ_FORNECEDOR;
CREATE SEQUENCE SQ_FORNECIMENTO_COMBUSTIVEL;
CREATE SEQUENCE SQ_FORNECIMENTO_PRODUTO_LOJA;
CREATE SEQUENCE SQ_FUNCIONARIO_CARGO;
CREATE SEQUENCE SQ_FUNCIONARIOS;
CREATE SEQUENCE SQ_PRODUTO_COMBUSTIVEL;
CREATE SEQUENCE SQ_PRODUTO_LOJA;
CREATE SEQUENCE SQ_TELEFONE;
CREATE SEQUENCE SQ_UF;
CREATE SEQUENCE SQ_ALERTAS_REABASTECIMENTO;
CREATE SEQUENCE SQ_GRATIFICACOES;
