-- Regra 4: Gratificação de Fim de Ano
CREATE OR REPLACE PROCEDURE PR_PAGAR_GRATIFICACAO_FIM_ANO (
  P_VALOR_BONUS IN NUMBER,
  P_DESCRICAO   IN VARCHAR2
)
IS
BEGIN
  INSERT INTO GRATIFICACOES (
    ID_GRATIFICACAO,
    ID_FUNCIONARIO,
    DATA_PAGAMENTO,
    VALOR_PAGAMENTO,
    DESCRICAO
  )
  SELECT
    SQ_GRATIFICACOES.NEXTVAL,
    F.ID_FUNCIONARIO,
    SYSDATE,
    P_VALOR_BONUS,
    P_DESCRICAO
  FROM FUNCIONARIOS F;

  DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' funcionários receberam a gratificação.');
  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
